"""add mood to script_paragraphs

Revision ID: 14b5325cfbd5
Revises: b2958178c90f
Create Date: 2026-03-29 14:22:59.594883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14b5325cfbd5'
down_revision = 'b2958178c90f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('script_paragraphs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mood', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('script_paragraphs', schema=None) as batch_op:
        batch_op.drop_column('mood')

    # ### end Alembic commands ###
