"""Add validation scores to recommended_topics

Revision ID: 5ab6b88ee572
Revises: bf762264cea0
Create Date: 2026-04-04 11:44:56.451943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ab6b88ee572'
down_revision = 'bf762264cea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommended_topics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score_history', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('score_channel_fit', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('score_audience', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('score_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('validation_details', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommended_topics', schema=None) as batch_op:
        batch_op.drop_column('validation_details')
        batch_op.drop_column('score_total')
        batch_op.drop_column('score_audience')
        batch_op.drop_column('score_channel_fit')
        batch_op.drop_column('score_history')

    # ### end Alembic commands ###
