"""Replace uq_script_paragraph with index

Revision ID: 8e191574677b
Revises: 5ab6b88ee572
Create Date: 2026-04-12 13:53:37.465706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e191574677b'
down_revision = '5ab6b88ee572'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('script_paragraphs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_script_paragraph'), type_='unique')
        batch_op.create_index('ix_script_paragraph_order', ['script_id', 'paragraph_index'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('script_paragraphs', schema=None) as batch_op:
        batch_op.drop_index('ix_script_paragraph_order')
        batch_op.create_unique_constraint(batch_op.f('uq_script_paragraph'), ['script_id', 'paragraph_index'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
