"""Add scene_images table

Revision ID: bf762264cea0
Revises: 14b5325cfbd5
Create Date: 2026-04-03 16:06:38.792750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf762264cea0'
down_revision = '14b5325cfbd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scene_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=False),
    sa.Column('scene_index', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('generation_id', sa.String(length=255), nullable=True),
    sa.Column('image_urls', sa.JSON(), nullable=True),
    sa.Column('selected_url', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scene_images')
    # ### end Alembic commands ###
